
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogbqxqrmtezezrcmkzkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nYnF4cXJtdGV6ZXpyY21remtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODQ1ODcsImV4cCI6MjA2MTE2MDU4N30.qM6UF2DLf0GsaelXW-6-1u3cQsADjROXB7NLzSceX1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
